# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-16 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sem', models.IntegerField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sem', models.IntegerField(max_length=20)),
                ('percentage', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('PhoneNum', models.CharField(max_length=15)),
                ('EmailAddress', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('RollNo', models.CharField(max_length=50)),
                ('PhoneNum', models.CharField(max_length=15)),
                ('EmailAddress', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=100)),
                ('Sem', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Sem', models.IntegerField(max_length=20)),
                ('Department', models.CharField(max_length=100)),
                ('FacultyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('UserType', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Students'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='SubjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='StudentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Students'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='SubjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subject'),
        ),
    ]
